### ISSUE TITLE
Here we can not work on back view 

### ISSUE THREAD

**Issue by harshilkotecha** [PrashantKT/BottomCardView#1]
you can just add any button on main view controller and its not clickable even popup is down 

![Screenshot 2020-06-19 at 1 16 03 AM](https://user-images.githubusercontent.com/9553649/85065273-80c31480-b1ca-11ea-9ee6-0c26bef58b77.png)

**Comment by PrashantKT** [comment]
@harshilkotecha  Thanks for feedback

Please checkout branch again and check  it is fixed now
